### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by PunkHaz4rd** [Scifabric/pybossa-client#11]
I get this error whenever i try to create a new application (even the flickrperson example app) :

File "/usr/local/lib/python2.7/dist-packages/pbclient/**init**.py", line 133, in find_app
    return [App(app_data) for app_data in _pybossa_req('get', 'app', params=kwargs)]
TypeError: 'int' object is not iterable

What can I do ? Thanks

**Comment by PunkHaz4rd** [comment]
Did you correct it ?

**Comment by teleyinex** [comment]
We cannot replicate it. We've been able to create several projects without it. Maybe it's the JSON. Can you try with the newest version? Wait until I merge #30

**Comment by PunkHaz4rd** [comment]
I was kidding, it was 4 years ago, I think I was using it during an internship or smth.

**Comment by teleyinex** [comment]
:-) Well, just in case you can now test the new version :D
