### ISSUE TITLE
Support client certificates with HTTPS endpoints

### ISSUE THREAD

**Issue by lasloo** [Scifabric/pybossa-client#24]
Would like to use pbclient against SSL endpoints that require local client certificates.

Potentially, the developer can use the "set(key,val)" function with "cert" and/or "verify" keys.   But then, the values associated with those keys do need to be explicitly passed to each "requests" call within the "_pybossa_req" function.

**Comment by teleyinex** [comment]
That's a really nice idea. We'll take a look at it.
